name: Welcome first-time-contributor

on:
  pull_request_target:
    types: [opened]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        pr-message: 'Congrats on making your first pull request 🎉. Thanks for taking the time to improve draw.calont.in !'
